[package]
name = "datadriven"
version = "0.1.0"
authors = ["accelsao <bebe8277@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
regex = "1"
lazy_static = "1"
slog = "2.7"
slog-term = "2.9"
slog-async = "2.8"
similar-asserts = "1"
